Repository nmstate/nmstate-console-plugin, pull requests merged in 2024-08, with the labels that each got.

#107 CNV-38365: OVN bridge mapping
  locales/en/plugin__nmstate-console-plugin.json
  package.json
  scripts/start-console.sh
  src/utils/components/PolicyForm/PolicyForm.tsx
  src/utils/components/PolicyForm/PolicyFormOVSBridgeMapping.tsx
  src/utils/components/PolicyForm/PolicyFormOVSBridgeMappingExpandable.tsx
  src/utils/components/PolicyForm/PolicyInterface.tsx
  src/utils/components/PolicyForm/PolicyInterfaceExpandable.tsx
  src/utils/components/PolicyForm/constants.ts
  src/utils/components/PolicyForm/utils.ts
  yarn.lock
Labels: approved, lgtm, jira/valid-reference

#105 Minor spelling/typo fix
  deployment/nmstate-console-plugin/Chart.yaml
  locales/en/plugin__nmstate-console-plugin.json
  plugin-manifest.ts
  src/utils/components/PolicyForm/PolicyForm.tsx
Labels: approved, lgtm

#108 NNS topology
  .github/workflows/on_pull_request.yaml
  cypress.config.ts
  cypress/e2e/NewPolicy.spec.cy.ts
  locales/en/plugin__nmstate-console-plugin.json
  package.json
  src/console-models/NodeNetworkStateModel.ts
  src/nmstate-types/custom-models/NodeNetworkConfigurationInterface.ts
  src/utils/components/DetailItem/DetailItem.scss
  src/utils/components/DetailItem/DetailItem.tsx
  src/utils/components/DetailItem/DetailItemHeader.tsx
  src/utils/components/DetailItem/EditButton.tsx
  src/utils/components/DetailItem/EditButtonWithTooltip.tsx
  src/utils/components/DetailItem/OwnerDetailItem.tsx
  src/utils/components/MetadataLabels/MetadataLabels.scss
  src/utils/components/MetadataLabels/MetadataLabels.tsx
  src/utils/components/OwnerReferences/OwnerReferences.tsx
  src/utils/components/Toggles/SelectToggle.tsx
  src/views/states/details/StateDetailsPage.tsx
  src/views/states/list/StatesList.tsx
  src/views/states/list/components/InterfaceDrawer/InterfaceDrawer.tsx
  src/views/states/list/constants.ts
  src/views/states/manifest.ts
  src/views/states/topology/Topology.tsx
  src/views/states/topology/components/CustomGroup.tsx
  src/views/states/topology/components/CustomNode.tsx
  src/views/states/topology/components/TopologySidebar/TopologySidebar.scss
  src/views/states/topology/components/TopologySidebar/TopologySidebar.tsx
  src/views/states/topology/components/TopologyToolbar/TopologyToolbar.scss
  src/views/states/topology/components/TopologyToolbar/TopologyToolbar.tsx
  src/views/states/topology/components/TopologyToolbar/TopologyToolbarFilter.tsx
  src/views/states/topology/utils/constants.ts
  src/views/states/topology/utils/factory.ts
  src/views/states/topology/utils/utils.ts
  tsconfig.json
  yarn.lock
Labels: approved

#109 Fix topology issues
  src/views/states/topology/Topology.tsx
  src/views/states/topology/components/CustomGroup/CustomGroup.scss
  src/views/states/topology/components/CustomGroup/CustomGroup.tsx
  src/views/states/topology/components/CustomNode/CustomNode.scss
  src/views/states/topology/components/CustomNode/CustomNode.tsx
  src/views/states/topology/utils/constants.ts
  src/views/states/topology/utils/factory.ts
  src/views/states/topology/utils/position.ts
  src/views/states/topology/utils/utils.ts
Labels: approved, lgtm
