Repository nmstate/nmstate-console-plugin, pull requests merged in 2024-10, with the labels that each got.

#113 fix tests for 4.17 and 4.18
  cypress/e2e/StatusList.spec.cy.ts
  cypress/support/selectors.ts
Labels: approved, lgtm

#114 OCPBUGS-42859: Interface with same name causes unexpected behavior in NNS topology
  src/views/states/list/StatesList.tsx
  src/views/states/topology/Topology.tsx
  src/views/states/topology/components/CustomNode/CustomNode.tsx
  src/views/states/topology/utils/position.ts
  src/views/states/topology/utils/utils.ts
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#115 CNV-49307: fix this for virt perspective
  src/views/policies/manifest.ts
Labels: approved, lgtm, jira/valid-reference
